# Generated by Django 6.0.7 on 2026-07-15 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTekshiruv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('natija', models.JSONField()),
                ('task_type', models.CharField(blank=True, max_length=10)),
                ('overall_band', models.FloatField(blank=True, null=True)),
                ('provider', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=50)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_tekshiruvlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Writing tekshiruvlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
