# Generated by Django 6.0.7 on 2026-07-15 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingTekshiruv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejim', models.CharField(choices=[('matn', 'Matn rejimi'), ('tezkor', 'Tezkor tahlil (audio)')], max_length=10)),
                ('matn', models.TextField(help_text='Kiritilgan matn yoki Azure transkripsiyasi')),
                ('audio_fayl', models.FileField(blank=True, upload_to='speaking/audio/')),
                ('natija', models.JSONField()),
                ('pronunciation', models.JSONField(blank=True, help_text='Azure Pronunciation natijasi (Tezkor rejimda)', null=True)),
                ('part_type', models.CharField(blank=True, max_length=10)),
                ('overall_band', models.FloatField(blank=True, help_text="Matn rejimida — Pronunciation'siz 3 mezon o'rtachasi", null=True)),
                ('provider', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=50)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_tekshiruvlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Speaking tekshiruvlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
