# Generated by Django 6.0.7 on 2026-08-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_speakingtekshiruv'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingtekshiruv',
            name='holat',
            field=models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tayyor', 'Tayyor'), ('xato', 'Xato')], default='tayyor', max_length=12),
        ),
        migrations.AddField(
            model_name='writingtekshiruv',
            name='holat',
            field=models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tayyor', 'Tayyor'), ('xato', 'Xato')], default='tayyor', max_length=12),
        ),
        migrations.AlterField(
            model_name='speakingtekshiruv',
            name='matn',
            field=models.TextField(blank=True, help_text='Kiritilgan matn yoki Azure transkripsiyasi'),
        ),
        migrations.AlterField(
            model_name='speakingtekshiruv',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='speakingtekshiruv',
            name='natija',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speakingtekshiruv',
            name='provider',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='writingtekshiruv',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='writingtekshiruv',
            name='natija',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writingtekshiruv',
            name='provider',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
