# Generated by Django 6.0.7 on 2026-07-15 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaketXarid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paket_turi', models.CharField(choices=[('5x5', '5x5'), ('10x10', '10x10')], max_length=10)),
                ('muddat_kun', models.PositiveIntegerField(choices=[(3, '3 kun'), (5, '5 kun'), (7, '7 kun')])),
                ('narx', models.PositiveIntegerField()),
                ('w_jami', models.PositiveIntegerField()),
                ('s_jami', models.PositiveIntegerField()),
                ('w_ishlatilgan', models.PositiveIntegerField(default=0)),
                ('s_ishlatilgan', models.PositiveIntegerField(default=0)),
                ('boshlanish', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paket_xaridlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Paket xaridlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
