# Generated by Django 6.0.7 on 2026-07-15 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='farzandlar',
            field=models.ManyToManyField(blank=True, help_text="Faqat 'Ota-ona' roli uchun — kuzatiladigan talabalar", limit_choices_to={'role': 'student'}, related_name='ota_onalar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('teacher', "O'qituvchi"), ('student', 'Talaba'), ('parent', 'Ota-ona')], default='student', max_length=10),
        ),
    ]
