# Generated by Django 6.0.7 on 2026-07-17 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_farzandlar_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='markaz',
            name='brend_rang',
            field=models.CharField(default='#FFD400', help_text='Markaz brendining asosiy rangi (hex, masalan #FFD400)', max_length=7),
        ),
        migrations.AddField(
            model_name='markaz',
            name='soruvchi',
            field=models.ForeignKey(blank=True, help_text="Markazni o'zi so'rab yuborgan foydalanuvchi (tasdiqlangach admin bo'ladi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorolgan_markazlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markaz',
            name='tasdiqlangan',
            field=models.BooleanField(default=True, help_text="False bo'lsa — owner tasdig'ini kutayotgan so'rov"),
        ),
    ]
