# Generated by Django 6.0.7 on 2026-07-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_markaz_brend_rang_markaz_soruvchi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markaz',
            name='api_key',
        ),
        migrations.AlterField(
            model_name='markaz',
            name='ai_provider',
            field=models.CharField(choices=[('claude', 'Claude'), ('gemini', 'Gemini')], default='gemini', help_text="Qaysi AI ishlatilsa ham, xarajat doim platforma (owner) kaliti orqali to'lanadi", max_length=10),
        ),
    ]
