# Generated by Django 6.0.7 on 2026-07-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_markaz_api_key_alter_markaz_ai_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('teacher', "O'qituvchi"), ('student', 'Talaba'), ('parent', 'Ota-ona'), ('oddiy', 'Oddiy foydalanuvchi')], default='student', max_length=10),
        ),
    ]
