# Generated by Django 6.0.7 on 2026-07-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='markaz',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook sahifa havolasi'),
        ),
        migrations.AddField(
            model_name='markaz',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram profil havolasi'),
        ),
        migrations.AddField(
            model_name='markaz',
            name='telegram',
            field=models.URLField(blank=True, help_text='Telegram kanal/guruh havolasi'),
        ),
        migrations.AddField(
            model_name='markaz',
            name='youtube',
            field=models.URLField(blank=True, help_text='YouTube kanal havolasi'),
        ),
    ]
