# Generated by Django 6.0.7 on 2026-07-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_markaz_facebook_markaz_instagram_markaz_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='korish_rejimi',
            field=models.CharField(blank=True, choices=[('owner', 'Owner (asl holat)'), ('admin', 'Administrator'), ('student', 'Talaba'), ('oddiy', 'Mehmon (oddiy foydalanuvchi)')], default='owner', help_text="Faqat owner uchun — 'Ko'rish rejimi' (View As) joriy tanlovi", max_length=10),
        ),
    ]
