# Generated by Django 6.0.7 on 2026-08-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_talabalar_markazsiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='korinadigan_panellar',
            field=models.JSONField(blank=True, default=None, help_text="Owner (istalgan foydalanuvchiga) yoki admin (faqat talabalarga) belgilaydigan QO'SHIMCHA cheklov (2026-08-05) — rolga asoslangan standart navigatsiya ustiga qo'yiladi, faqat TORAYTIRADI, KENGAYTIRMAYDI. null/bo'sh = cheklovsiz (rol bo'yicha standart). Ro'yxat elementlari nav yo'llari (masalan '/kurslar').", null=True),
        ),
    ]
