# Generated by Django 6.0.7 on 2026-08-08 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_korinadigan_panellar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bildirishnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('reliz', 'Yangilanish')], default='reliz', max_length=20)),
                ('kalit', models.CharField(max_length=200)),
                ('sarlavha', models.CharField(max_length=300)),
                ('matn', models.TextField(blank=True)),
                ('oqilgan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirishnomalar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('foydalanuvchi', 'kalit'), name='bildirishnoma_kalit_takrorlanmasin')],
            },
        ),
    ]
