# Generated by Django 6.0.7 on 2026-08-09 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_bildirishnoma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='farzandlar',
        ),
        migrations.AddField(
            model_name='user',
            name='ota_ona',
            field=models.ForeignKey(blank=True, help_text="Faqat 'Talaba' roli uchun — kuzatuvchi ota-ona (bitta)", limit_choices_to={'role': 'parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farzandlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='rasm',
            field=models.ImageField(blank=True, help_text="Profil rasmi (2026-08-09). R2 bucket YOPIQ, shuning uchun to'g'ridan-to'g'ri URL bilan emas, autentifikatsiyalangan endpoint orqali uzatiladi — `FoydalanuvchiRasmView`.", upload_to='foydalanuvchi_rasm/'),
        ),
    ]
