# Generated by Django 6.0.7 on 2026-08-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_farzandlar_user_ota_ona_user_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildirishnoma',
            name='turi',
            field=models.CharField(choices=[('reliz', 'Yangilanish'), ('ogohlantirish', 'Ogohlantirish')], default='reliz', max_length=20),
        ),
    ]
