# Generated by Django 6.0.7 on 2026-08-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_bildirishnoma_turi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='korish_rejimi',
            field=models.CharField(blank=True, choices=[('owner', 'Owner (asl holat)'), ('admin', 'Administrator'), ('student', 'Talaba'), ('parent', 'Ota-ona'), ('oddiy', 'Mehmon (oddiy foydalanuvchi)')], default='owner', help_text="Faqat owner uchun — 'Ko'rish rejimi' (View As) joriy tanlovi", max_length=10),
        ),
    ]
