# Generated by Django 6.0.7 on 2026-08-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_korish_rejimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qurilma_id',
            field=models.CharField(blank=True, default='', help_text="Hisobni boshqalar bilan bo'lishmaslik uchun (2026-08-12) — OWNER'dan boshqa har bir foydalanuvchi FAQAT birinchi muvaffaqiyatli login qilgan brauzeriga bog'lanadi (frontend localStorage'da saqlagan tasodifiy ID). Bo'sh = hali hech qaysi qurilmaga bog'lanmagan (keyingi login avtomatik bog'laydi). Faqat owner/admin 'Qurilmani tiklash' orqali tozalay oladi — `XodimLoginView`/`QurilmaTiklashView`ga qarang.", max_length=64),
        ),
    ]
