# Generated by Django 6.0.7 on 2026-08-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_qurilma_id'),
    ]

    def qurilma_id_kochir(apps, schema_editor):
        """Eski bitta-qurilmali `qurilma_id`ni yangi `qurilmalar`
        ro'yxatiga ko'chiradi — hozirgacha qulflangan hisoblar
        migratsiyadan keyin qayta login qilishga majbur bo'lmasin."""
        User = apps.get_model('accounts', 'User')
        for u in User.objects.exclude(qurilma_id='').only('id', 'qurilma_id'):
            User.objects.filter(pk=u.pk).update(qurilmalar=[u.qurilma_id])

    operations = [
        migrations.AddField(
            model_name='user',
            name='qurilma_limiti',
            field=models.PositiveSmallIntegerField(default=1, help_text="2026-08-13 — nechta qurilmadan bir vaqtda kirish mumkinligi (standart 1). Hozircha FAQAT owner o'zgartira oladi (`QurilmaLimitiView`) — kelajakda adminga ham berilishi mumkin (foydalanuvchi qarori)."),
        ),
        migrations.AddField(
            model_name='user',
            name='qurilmalar',
            field=models.JSONField(blank=True, default=list, help_text="Hisobni boshqalar bilan bo'lishmaslik uchun (2026-08-12, 2026-08-13'da ko'p-qurilmali qilib kengaytirildi) — OWNER'dan boshqa har bir foydalanuvchi FAQAT shu ro'yxatdagi qurilmalardan (frontend localStorage'dagi tasodifiy ID'lar) kira oladi. Yangi qurilma `qurilma_limiti`ga yetmagunча AVTOMATIK qo'shiladi (keyingi login), limit to'lgach rad etiladi. Bo'sh ro'yxat = hali hech qaysi qurilmaga bog'lanmagan. Faqat owner/admin 'Qurilmani tiklash' orqali TO'LIQ tozalay oladi (limitga tegmasdan) — `XodimLoginView`/`QurilmaTiklashView`ga qarang."),
        ),
        migrations.RunPython(qurilma_id_kochir, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='qurilma_id',
        ),
    ]
