# Generated by Django 6.0.7 on 2026-08-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_user_qurilma_id_user_qurilma_limiti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text="'O'zim haqimda' — qisqa erkin matn", max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='maqsad_band',
            field=models.CharField(blank=True, choices=[('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('5.5', '5.5'), ('6.0', '6.0'), ('6.5', '6.5'), ('7.0', '7.0'), ('7.5', '7.5'), ('8.0', '8.0'), ('8.5', '8.5'), ('9.0', '9.0')], help_text="Maqsad IELTS band bahosi (masalan '8.0')", max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='maqsad_muddat',
            field=models.DateField(blank=True, help_text='Maqsadga qadar muddat', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sabab',
            field=models.CharField(blank=True, choices=[('oqish', "Chet elda o'qish"), ('ish', 'Ish/immigratsiya'), ('shaxsiy', 'Shaxsiy rivojlanish'), ('boshqa', 'Boshqa')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='telefon',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tugilgan_sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
