# Generated by Django 6.0.7 on 2026-08-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_bio_user_maqsad_band_user_maqsad_muddat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='maqsad_band',
        ),
        migrations.RemoveField(
            model_name='user',
            name='maqsad_muddat',
        ),
        migrations.AddField(
            model_name='user',
            name='maqsad',
            field=models.TextField(blank=True, help_text="Erkin matn, masalan 'IELTS 8.0'", max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='sabab',
            field=models.TextField(blank=True, help_text="Nima uchun o'qiyapti — erkin matn", max_length=500),
        ),
    ]
