# Generated by Django 6.0.7 on 2026-08-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_user_maqsad_band_remove_user_maqsad_muddat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='maqsad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sabab',
        ),
        migrations.AddField(
            model_name='user',
            name='ota_ona_telefon',
            field=models.CharField(blank=True, help_text='Ota-ona/vasiy telefon raqami', max_length=20),
        ),
    ]
