# Generated by Django 6.0.7 on 2026-08-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_user_maqsad_remove_user_sabab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='markaz',
            name='kirish_cheklangan',
            field=models.BooleanField(default=False),
        ),
    ]
