# Generated by Django 6.0.7 on 2026-08-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_markaz_kirish_cheklangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('teacher', "O'qituvchi"), ('student', 'Talaba'), ('parent', 'Ota-ona'), ('oddiy', 'Oddiy foydalanuvchi')], db_index=True, default='student', max_length=10),
        ),
    ]
