# Generated by Django 6.0.7 on 2026-09-04 05:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='markaz',
            name='zaxira_avtomatik',
            field=models.BooleanField(default=False, help_text='Har kuni belgilangan vaqtda baza zaxirasi olinsinmi'),
        ),
        migrations.AddField(
            model_name='markaz',
            name='zaxira_saqlash_kuni',
            field=models.PositiveSmallIntegerField(default=7, help_text="Zaxira R2'da shuncha kun saqlanadi; muddati o'tgani o'chiriladi (eng oxirgisi har doim qoladi)"),
        ),
        migrations.AddField(
            model_name='markaz',
            name='zaxira_vaqti',
            field=models.TimeField(default=datetime.time(3, 0), help_text="Mahalliy vaqt (Asia/Tashkent) — shu vaqtdan keyingi birinchi so'rovda olinadi"),
        ),
        migrations.CreateModel(
            name='Zaxira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('turi', models.CharField(choices=[('avtomatik', 'Avtomatik'), ('qolda', "Qo'lda")], default='avtomatik', max_length=10)),
                ('fayl', models.FileField(blank=True, upload_to='zaxiralar/')),
                ('hajm', models.PositiveBigIntegerField(default=0, help_text='Bayt')),
                ('xato', models.TextField(blank=True, help_text='Zaxira olinmasa — sababi')),
                ('yuklab_olindi', models.BooleanField(default=False)),
                ('yuklab_olingan_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('markaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaxiralar', to='accounts.markaz')),
            ],
            options={
                'verbose_name_plural': 'Zaxiralar',
                'ordering': ['-sana', '-id'],
                'unique_together': {('markaz', 'sana', 'turi')},
            },
        ),
    ]
