# Generated by Django 6.0.7 on 2026-09-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_markaz_zaxira_avtomatik_markaz_zaxira_saqlash_kuni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oxirgi_faollik',
            field=models.DateTimeField(blank=True, help_text="Oxirgi API so'rovi vaqti — 'Aktiv foydalanuvchilar' ro'yxati uchun", null=True),
        ),
    ]
