# Generated by Django 6.0.7 on 2026-09-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_oxirgi_faollik'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zaxira',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='zaxira',
            constraint=models.UniqueConstraint(condition=models.Q(('turi', 'avtomatik')), fields=('markaz', 'sana'), name='zaxira_kunda_bitta_avtomatik'),
        ),
    ]
