# Generated by Django 6.0.7 on 2026-09-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_zaxira_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_maydonlari',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='izoh',
            field=models.CharField(blank=True, help_text='Admin izohi', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='manba',
            field=models.CharField(blank=True, help_text='Talaba qayerdan kelgan', max_length=100),
        ),
    ]
