# Generated by Django 6.0.7 on 2026-09-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_talaba_qoshimcha_malumot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ota_ona_ismi',
            field=models.CharField(blank=True, help_text='Ota-ona/vasiy ismi (masalan: onasi Nilufar)', max_length=100),
        ),
    ]
