# Generated by Django 6.0.7 on 2026-09-25 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_ota_ona_ismi'),
    ]

    operations = [
        migrations.CreateModel(
            name='OchirilganFoydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foydalanuvchi_id', models.PositiveIntegerField(help_text="O'chirilgan foydalanuvchining asl ID'si")),
                ('username', models.CharField(max_length=150)),
                ('ism', models.CharField(blank=True, max_length=300)),
                ('rol', models.CharField(max_length=20)),
                ('ochirilgan_vaqt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('obyektlar', models.TextField(help_text='django.core.serializers JSON')),
                ('bogliqlar', models.JSONField(default=list, help_text='[{model, maydon, pklar}] — SET_NULL bilan uzilganlar')),
                ('soni', models.PositiveIntegerField(default=0, help_text='Nusxadagi yozuvlar soni')),
                ('ochirgan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "O'chirilgan foydalanuvchilar",
                'ordering': ['-ochirilgan_vaqt', '-id'],
            },
        ),
    ]
