# Generated by Django 6.0.7 on 2026-10-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_ochirilgan_foydalanuvchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildirishnoma',
            name='havola',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
