# Generated by Django 6.0.7 on 2026-10-04 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otabot', '0002_sorov_bildirishnomalari_havolasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='otabotkuzatuv',
            name='davomat_boshlandi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Xabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=20)),
                ('kalit', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('yuborilsin', models.DateTimeField(db_index=True)),
                ('holat', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('yuborildi', 'Yuborildi'), ('bekor', 'Bekor qilindi'), ('xato', 'Xato')], db_index=True, default='kutilmoqda', max_length=12)),
                ('urinish', models.PositiveSmallIntegerField(default=0)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yuborildi', models.DateTimeField(blank=True, null=True)),
                ('abonent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xabarlar', to='otabot.abonent')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('abonent', 'kalit'), name='otabot_xabar_unikal')],
            },
        ),
    ]
