# Generated by Django 6.0.7 on 2026-10-04 18:31

import datetime
import django.db.models.deletion
import parentsbot.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('ism', models.CharField(blank=True, max_length=200)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('til', models.CharField(default='uz', max_length=2)),
                ('holat', models.CharField(choices=[('til', 'Til tanlash'), ('telefon', 'Telefon kutilmoqda'), ('farzand_ism', 'Farzand ismi kutilmoqda'), ('farzand_sana', "Tug'ilgan sana kutilmoqda"), ('tayyor', 'Tayyor')], default='til', max_length=20)),
                ('kontekst', models.JSONField(blank=True, default=dict)),
                ('faol', models.BooleanField(default=True)),
                ('toifa_ochirilgan', models.JSONField(blank=True, default=list)),
                ('urinishlar', models.JSONField(blank=True, default=list)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ota-ona (Telegram)',
            },
        ),
        migrations.CreateModel(
            name='ParentsBotKuzatuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxirgi_update_id', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ParentsBotSozlama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('davomat_yoqilgan', models.BooleanField(default=True)),
                ('davomat_kelmadi', models.BooleanField(default=True)),
                ('davomat_kechikdi', models.BooleanField(default=True)),
                ('davomat_sababli', models.BooleanField(default=False)),
                ('tolov_yoqilgan', models.BooleanField(default=True)),
                ('qarz_yoqilgan', models.BooleanField(default=True)),
                ('qarz_kunlari', models.JSONField(default=parentsbot.models._dushanba)),
                ('qarz_soati', models.TimeField(default=datetime.time(10, 0))),
                ('natija_yoqilgan', models.BooleanField(default=True)),
                ('natija_kunlari', models.JSONField(default=parentsbot.models._hamma_kunlar)),
                ('natija_soati', models.TimeField(default=datetime.time(19, 0))),
                ('tinch_boshi', models.TimeField(default=datetime.time(22, 0))),
                ('tinch_oxiri', models.TimeField(default=datetime.time(8, 0))),
                ('yangilangan', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ota-ona boti sozlamasi',
            },
        ),
        migrations.CreateModel(
            name='Sorov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farzand_ismi', models.CharField(max_length=200)),
                ('tugilgan_sana', models.CharField(blank=True, max_length=30)),
                ('nomzodlar', models.JSONField(blank=True, default=list)),
                ('holat', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('ulandi', 'Ulandi'), ('rad', 'Rad etildi')], db_index=True, default='kutilmoqda', max_length=12)),
                ('hal_vaqti', models.DateTimeField(blank=True, null=True)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('abonent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorovlar', to='parentsbot.abonent')),
                ('hal_qilgan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('talaba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-yaratilgan'],
            },
        ),
        migrations.CreateModel(
            name='Boglanish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usul', models.CharField(choices=[('telefon', 'Telefon raqami'), ('ism_sana', "Ism va tug'ilgan sana"), ('admin', 'Admin ulagan')], max_length=10)),
                ('faol', models.BooleanField(default=True)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('abonent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boglanishlar', to='parentsbot.abonent')),
                ('kim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('talaba', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='ota_bot_boglanishlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('abonent', 'talaba'), name='parentsbot_boglanish_unikal')],
            },
        ),
    ]
