# Generated by Django 6.0.7 on 2026-10-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentsbot', '0003_otabotkuzatuv_davomat_boshlandi_xabar'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentsbotkuzatuv',
            name='tolov_boshlandi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
