# Generated by Django 6.0.7 on 2026-10-04 22:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentsbot', '0004_kuzatuv_tolov_boshlandi'),
    ]

    operations = [
        migrations.AddField(
            model_name='boglanish',
            name='faollashgan',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parentsbotkuzatuv',
            name='natija_skanlandi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentsbotkuzatuv',
            name='qarz_skanlandi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
