# Generated by Django 6.0.7 on 2026-10-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentsbot', '0005_faollashgan_skanlandi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonent',
            name='toifa_ochirilgan',
        ),
        migrations.AddField(
            model_name='abonent',
            name='bloklangan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
