# Generated by Django 6.0.7 on 2026-10-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parentsbot', '0006_abonent_bloklangan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentsbotsozlama',
            options={'verbose_name': 'Ota-ona nazorati sozlamasi'},
        ),
    ]
