# Generated by Django 6.0.7 on 2026-10-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentsbot', '0007_ota_ona_nazorati_nomi'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentsbotkuzatuv',
            name='keldi_boshlandi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentsbotkuzatuv',
            name='yechim_boshlandi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentsbotsozlama',
            name='davomat_keldi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parentsbotsozlama',
            name='ielts_rejimi',
            field=models.CharField(choices=[('ochiq', "O'chiq"), ('darhol', 'Darhol'), ('yigma', "Kunlik yig'mada")], default='darhol', max_length=6),
        ),
        migrations.AddField(
            model_name='parentsbotsozlama',
            name='soz_rejimi',
            field=models.CharField(choices=[('ochiq', "O'chiq"), ('darhol', 'Darhol'), ('yigma', "Kunlik yig'mada")], default='darhol', max_length=6),
        ),
        migrations.AddField(
            model_name='parentsbotsozlama',
            name='ws_rejimi',
            field=models.CharField(choices=[('ochiq', "O'chiq"), ('darhol', 'Darhol'), ('yigma', "Kunlik yig'mada")], default='darhol', max_length=6),
        ),
    ]
