# Generated by Django 6.0.7 on 2026-07-21 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KursTugun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('ikonka', models.CharField(blank=True, help_text='Emoji ikonka (masalan 🇬🇧, 📖)', max_length=10)),
                ('tartib', models.PositiveSmallIntegerField(default=0)),
                ('tez_kunda', models.BooleanField(default=False, help_text="Hali kontent tayyor emas (masalan Rus tili/Matematika) — bo'sh, 'tez kunda' deb ko'rsatiladi")),
                ('fayl', models.FileField(blank=True, help_text='Faqat oxirgi qatlam (farzandsiz) tugunlarda ishlatiladi', upload_to='kurslar/fayllar/')),
                ('markaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurs_tugunlari', to='accounts.markaz')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.kurstugun')),
            ],
            options={
                'verbose_name_plural': 'Kurs tugunlari',
                'ordering': ['tartib', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KursProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurs_progresslari', to=settings.AUTH_USER_MODEL)),
                ('tugun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresslar', to='courses.kurstugun')),
            ],
            options={
                'verbose_name_plural': 'Kurs progresslari',
                'constraints': [models.UniqueConstraint(fields=('talaba', 'tugun'), name='kurs_progress_unikal')],
            },
        ),
    ]
