# Generated by Django 6.0.7 on 2026-07-21 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KursMashq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tartib', models.PositiveSmallIntegerField(default=0)),
                ('matn', models.TextField(blank=True, help_text='Topshiriq/passage matni (ixtiyoriy)')),
                ('rasm', models.ImageField(blank=True, help_text='Masalan darslikdagi rasmli savol (nechta narsa bor va h.k.)', upload_to='kurslar/mashq_rasm/')),
                ('savollar', models.JSONField(default=list, help_text='[{"savol": "...", "variantlar": [...] (ixtiyoriy), "togri": "..."}]')),
                ('tugun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mashqlar', to='courses.kurstugun')),
            ],
            options={
                'verbose_name_plural': 'Kurs mashqlari',
                'ordering': ['tartib', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KursMashqYechim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('javoblar', models.JSONField()),
                ('ball', models.PositiveIntegerField()),
                ('jami', models.PositiveIntegerField()),
                ('natijalar', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mashq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yechimlar', to='courses.kursmashq')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurs_mashq_yechimlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kurs mashq yechimlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
