# Generated by Django 6.0.7 on 2026-07-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_kurstugun_unit_darsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurstugun',
            name='unit_darsi',
            field=models.BooleanField(default=False, help_text="Ketma-ket o'tiladigan dars (masalan darslik Unit'i). Shu belgi qo'yilgan tugunlar bir xil ota-tugun ostida tartib bo'yicha ketma-ket ochiladi — talaba uchun keyingisi oldingisining BARCHA bo'limlaridagi mashqlardan jami 60%+ ball olmaguncha qulflangan bo'ladi."),
        ),
    ]
