# Generated by Django 6.0.7 on 2026-07-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_kurstugun_unit_darsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kursmashq',
            name='audio',
            field=models.FileField(blank=True, help_text="Darslikdagi audio (masalan Listening bo'limi uchun)", upload_to='kurslar/mashq_audio/'),
        ),
    ]
