# Generated by Django 6.0.7 on 2026-07-27 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_kursmashq_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurstugun',
            name='matn',
            field=models.TextField(blank=True, help_text="Sof matnli tugunlar uchun (masalan 'Grammar reference' — Unit bo'yicha qisqa grammatika xulosasi). Fayl emas, chunki AI buni to'g'ridan-to'g'ri matn sifatida generatsiya qiladi (2026-07-27, Unit'ni bitta so'rovda yuklash imkoniyati)."),
        ),
        migrations.CreateModel(
            name='KursSoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tartib', models.PositiveSmallIntegerField(default=0)),
                ('en', models.CharField(max_length=200)),
                ('uz', models.CharField(max_length=300)),
                ('turkum', models.CharField(blank=True, help_text="So'z turkumi (ixtiyoriy)", max_length=50)),
                ('misol', models.TextField(blank=True, help_text='Namuna gap (ixtiyoriy)')),
                ('tugun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sozlar', to='courses.kurstugun')),
            ],
            options={
                'verbose_name_plural': "Kurs so'zlari",
                'ordering': ['tartib', 'id'],
            },
        ),
    ]
