# Generated by Django 6.0.7 on 2026-07-27 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_kurstugun_matn_kurssoz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurstugun',
            name='matn',
            field=models.TextField(blank=True, help_text="Sof matnli tugunlar uchun (masalan 'Vocabulary' — shu Unit bo'yicha qisqa grammatika xulosasi, so'zlar ro'yxati bilan BIR sahifada keladi). Fayl emas, chunki AI buni to'g'ridan-to'g'ri matn sifatida generatsiya qiladi (2026-07-27, Unit'ni bitta so'rovda yuklash imkoniyati)."),
        ),
        migrations.CreateModel(
            name='KursMashqAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='kurslar/mashq_audio_royxat/')),
                ('raqam', models.CharField(blank=True, help_text="Darslikdagi track raqami (masalan '1.01') — faqat ma'lumot uchun", max_length=20)),
                ('tartib', models.PositiveSmallIntegerField(default=0)),
                ('mashq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiolar', to='courses.kursmashq')),
            ],
            options={
                'verbose_name_plural': 'Kurs mashq audiolari',
                'ordering': ['tartib', 'id'],
            },
        ),
    ]
