# Generated by Django 6.0.7 on 2026-07-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_kurstugun_matn_kursmashqaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurstugun',
            name='kalit',
            field=models.CharField(blank=True, db_index=True, help_text='Barqaror identifikator (masalan \'mashqlar\', \'vocabulary\', \'students_book\'). 2026-07-28 da qo\'shildi: avval tugunni NOMI bo\'yicha topardik (backendda `bolalar["Mashqlar"]`, frontendda `nomi === "Vocabulary"`), lekin nomlar 3 tilda ko\'rsatiladigan bo\'lgach bu yo\'l sinadi. Endi kod HAR DOIM shu kalitga tayanadi, `nomi` esa faqat zaxira ko\'rinish (kaliti yo\'q tugunlar uchun). Kalit GLOBAL unikal EMAS — \'vocabulary\' bir necha joyda uchraydi, muhimi bitta ota-tugun ichida takrorlanmasligi.', max_length=50),
        ),
    ]
