# Generated by Django 6.0.7 on 2026-07-28 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_kurstugun_kalit'),
    ]

    operations = [
        migrations.AddField(
            model_name='kursmashq',
            name='bloklar',
            field=models.JSONField(blank=True, default=list, help_text="Darslik sahifasining STRUKTURALI ko'rinishi (2026-07-28). Bo'sh bo'lsa — eski ko'rinish ishlaydi (sahifa rasmi + ustida foizli pozitsiyadagi input'lar). To'ldirilgan bo'lsa — sahifa qaytadan quriladi: matn haqiqiy HTML matni (o'tkir, tanlanadi, tarjima qilinadi), suratlar `KursMashqRasmi` sifatida alohida kesib olinadi.\n\nMUHIM: bo'sh joylar (input'lar) BU YERDA SAQLANMAYDI — ular `savollar` massiviga yassilanadi, blok esa faqat `savol_idx` orqali ishora qiladi. Shu tufayli javob tekshirish, ball, 60% qoidasi va Unit qulfi mexanizmiga UMUMAN TEGILMAYDI."),
        ),
        migrations.CreateModel(
            name='KursMashqRasmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tartib', models.PositiveSmallIntegerField(default=0)),
                ('rasm', models.ImageField(upload_to='kurslar/blok_rasm/')),
                ('izoh', models.CharField(blank=True, help_text='Nima tasvirlangani (alt matni) — AI beradi', max_length=200)),
                ('mashq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='courses.kursmashq')),
            ],
            options={
                'verbose_name_plural': 'Kurs mashq rasmlari',
                'ordering': ['tartib', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KursZipJarayoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_fayl', models.FileField(upload_to='kurslar/zip_jarayon/')),
                ('holat', models.CharField(choices=[('yangi', 'Yangi'), ('ishlanmoqda', 'Ishlanmoqda'), ('tugadi', 'Tugadi'), ('xato', 'Xato')], default='yangi', max_length=20)),
                ('jami_sahifa', models.PositiveSmallIntegerField(default=0)),
                ('ishlangan_sahifa', models.PositiveSmallIntegerField(default=0)),
                ('natijalar', models.JSONField(blank=True, default=dict, help_text="Oraliq natijalar: sahifa tahlillari, javob kaliti bandlari, xatolar. Javob kaliti odatda MASHQ sahifalaridan KEYIN keladi, shuning uchun bazaga yozish oxirida bir yo'la bajariladi.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tugun', models.ForeignKey(help_text="KITOB tuguni (Student's Book / Workbook)", on_delete=django.db.models.deletion.CASCADE, related_name='zip_jarayonlari', to='courses.kurstugun')),
            ],
            options={
                'verbose_name_plural': 'Kurs ZIP jarayonlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
