# Generated by Django 6.0.7 on 2026-08-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_kursmashq_bloklar_kursmashqrasmi_kurszipjarayoni'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurszipjarayoni',
            name='manba_turi',
            field=models.CharField(choices=[('zip', 'ZIP (rasmlar)'), ('pdf', 'PDF (kitob)')], default='zip', max_length=10),
        ),
        migrations.AlterField(
            model_name='kurszipjarayoni',
            name='holat',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('ishlanmoqda', 'Ishlanmoqda'), ('tasdiq_kutilmoqda', 'Tasdiqlash kutilmoqda'), ('tugadi', 'Tugadi'), ('xato', 'Xato')], default='yangi', max_length=20),
        ),
    ]
