# Generated by Django 6.0.7 on 2026-08-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_kurszipjarayoni_manba_turi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kursmashq',
            name='audio_kerak',
            field=models.BooleanField(default=False, help_text="Blok-mashq tasdiqlashda belgilanadi (2026-08-05) — PDF'da audio ikonkasi bor, lekin audio faylining o'zi PDF'dan chiqmaydi, admin alohida yuklashi kerak. Faqat ogohlantirish uchun, hech narsani bloklamaydi."),
        ),
    ]
