# Generated by Django 6.0.7 on 2026-08-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_kursmashq_audio_kerak'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurszipjarayoni',
            name='rejim',
            field=models.CharField(choices=[('blok', 'Blok formati (sahifa qayta quriladi)'), ('rasm_fon', 'Rasm-fon (sahifa rasm, javoblar ustida)')], default='blok', max_length=10),
        ),
    ]
