# Generated by Django 6.0.7 on 2026-08-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_kurszipjarayoni_rejim'),
    ]

    operations = [
        migrations.AddField(
            model_name='kursmashqaudio',
            name='fayl_xesh',
            field=models.CharField(blank=True, db_index=True, help_text='Audio faylning SHA-256 yig\'indisi (2026-08-08, foydalanuvchi talabi: "bir xil audio ikki marta yuklanmasin"). Bir xil xeshli yozuv topilsa yangi fayl YOZILMAYDI — mavjud faylning o\'zi ko\'rsatiladi. Shu sababli BIR fayliga bir nechta yozuv ishora qilishi mumkin; faylni o\'chirishdan oldin boshqa yozuvlar foydalanmayotganini tekshirish SHART (`courses.views._audio_faylini_xavfsiz_ochir`).', max_length=64),
        ),
    ]
