# Generated by Django 6.0.7 on 2026-08-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_kursmashqaudio_fayl_xesh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurszipjarayoni',
            name='manba_turi',
            field=models.CharField(choices=[('zip', 'ZIP (rasmlar)')], default='zip', max_length=10),
        ),
        migrations.AlterField(
            model_name='kurszipjarayoni',
            name='rejim',
            field=models.CharField(choices=[('blok', 'Blok formati (sahifa qayta quriladi)')], default='blok', max_length=10),
        ),
    ]
