# Generated by Django 6.0.7 on 2026-08-09 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_kurszipjarayoni_manba_turi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kursmashq',
            name='fon_rejimi',
            field=models.BooleanField(default=False, help_text="2026-08-09: admin qo'lda belgilaydi. True — rasm FON bo'lib qoladi, savollar (pozitsiya bilan) rasm ustiga chiqadi. False (standart) — rasm tepada, savollar oddiy ro'yxatda."),
        ),
        migrations.CreateModel(
            name='KursMashqRasmGuruhi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='kurslar/mashq_rasm_guruhi/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tugun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasm_guruhlari', to='courses.kurstugun')),
            ],
        ),
        migrations.AddField(
            model_name='kursmashq',
            name='rasm_guruhi',
            field=models.ForeignKey(blank=True, help_text="To'ldirilgan bo'lsa, rasm shu YERDAN olinadi (o'z `rasm` maydoni e'tiborga olinmaydi) — bir nechta mashq bitta rasmni ulashishi uchun.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mashqlar', to='courses.kursmashqrasmguruhi'),
        ),
    ]
