# Generated by Django 6.0.7 on 2026-08-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_kursmashq_fon_rejimi_kursmashqrasmguruhi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kursmashq',
            name='fon_rejimi',
        ),
        migrations.AddField(
            model_name='kursmashqrasmguruhi',
            name='tomon',
            field=models.CharField(choices=[('tepa', 'Matn tepasida'), ('past', 'Matn ostida'), ('chap', 'Matnning chapida'), ('ong', "Matnning o'ngida")], default='chap', help_text='Ulashilgan rasm mashqlarga nisbatan qayerda turadi (admin tanlaydi)', max_length=10),
        ),
    ]
