# Generated by Django 6.0.7 on 2026-08-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_kursmashq_fon_rejimi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurssoz',
            name='manba',
            field=models.CharField(choices=[('students_book', "Student's Book"), ('workbook', 'Workbook')], default='students_book', help_text="2026-08-19: Vocabulary Unit darajasida BITTA (Student's Book va Workbook ulashadi), lekin har so'z qaysi kitobdan kelganini shu maydon orqali eslab qoladi — 'Tozalash' faqat shu kitobga tegishli so'zlarni o'chirishi uchun. Talabaga ko'rinmaydi (faqat backend mantig'i).", max_length=15),
        ),
        migrations.AddField(
            model_name='kurstugun',
            name='matn_workbook',
            field=models.TextField(blank=True, help_text="Vocabulary tugunining Workbook manbasidan kelgan matni — `matn` (Student's Book) bilan bir xil tugunda, lekin alohida saqlanadi, chunki 'Tozalash' faqat BITTA kitobning ulushini o'chirishi kerak (2026-08-19, foydalanuvchi talabi: Vocabulary Unit uchun umumiy, lekin manba backendda kuzatiladi, foydalanuvchiga ko'rinmaydi)."),
        ),
        migrations.AlterField(
            model_name='kurstugun',
            name='matn',
            field=models.TextField(blank=True, help_text="Sof matnli tugunlar uchun (masalan 'Vocabulary' — shu Unit bo'yicha qisqa grammatika xulosasi, so'zlar ro'yxati bilan BIR sahifada keladi). Fayl emas, chunki AI buni to'g'ridan-to'g'ri matn sifatida generatsiya qiladi (2026-07-27, Unit'ni bitta so'rovda yuklash imkoniyati). 2026-08-19dan buyon Vocabulary tuguni UNIT darajasida BITTA — bu maydon Student's Book manbasidan kelgan matnni saqlaydi, Workbook'niki `matn_workbook`da (pastga qarang)."),
        ),
    ]
