# Generated by Django 6.0.7 on 2026-09-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_kurssoz_manba_kurstugun_matn_workbook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurssoz',
            name='ru',
            field=models.CharField(blank=True, help_text='2026-09-05, foydalanuvchi talabi: ruscha tarjima. Bo\'sh bo\'lishi mumkin — bosqichma-bosqich to\'ldiriladi (Vocabulary bo\'limidagi "Rus tiliga tarjima qilish" tugmasi, `courses.soz_tarjima`). Bo\'sh bo\'lsa hamma joyda `uz` ishlatiladi, shuning uchun yarim to\'ldirilgan holat hech narsani buzmaydi.', max_length=300),
        ),
    ]
