# Generated by Django 6.0.7 on 2026-10-08 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_intermediate_mashq_shakllari'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KursSozYechim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.PositiveIntegerField()),
                ('jami', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurs_soz_yechimlari', to=settings.AUTH_USER_MODEL)),
                ('tugun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soz_yechimlari', to='courses.kurstugun')),
            ],
            options={
                'verbose_name_plural': "Kurs so'z yechimlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
