# Generated by Django 6.0.7 on 2026-07-21 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaoliyatYozuvi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harakat', models.CharField(choices=[('yaratish', 'Yaratish'), ('ozgartirish', "O'zgartirish"), ('ochirish', "O'chirish")], max_length=15)),
                ('obyekt_turi', models.CharField(help_text="masalan 'Mashq', 'ImtihonTest', 'Foydalanuvchi', 'Guruh', 'Markaz'", max_length=40)),
                ('obyekt_id', models.PositiveIntegerField(blank=True, null=True)),
                ('obyekt_nomi', models.CharField(help_text="O'qiladigan nom (snapshot) — obyekt o'chirilgandan keyin ham qolishi uchun", max_length=200)),
                ('ozgarishlar', models.JSONField(blank=True, default=dict, help_text="yaratish/o'chirish: to'liq snapshot; o'zgartirish: {maydon: {eski, yangi}} — faqat o'zgargan maydonlar")),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(help_text='Harakatni bajargan admin/owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faoliyat_yozuvlari', to=settings.AUTH_USER_MODEL)),
                ('markaz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faoliyat_yozuvlari', to='accounts.markaz')),
            ],
            options={
                'verbose_name_plural': 'Faoliyat yozuvlari',
                'ordering': ['-vaqt'],
            },
        ),
    ]
