# Generated by Django 6.0.7 on 2026-08-05 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(help_text="Login paytidagi rol snapshoti (keyin o'zgarishi mumkin)", max_length=10)),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_tarixi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Login tarixi',
                'ordering': ['-vaqt'],
            },
        ),
    ]
