# Generated by Django 6.0.7 on 2026-07-15 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mashq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bolim', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading')], max_length=10)),
                ('tur', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blanks', 'Fill in the Blanks'), ('matching', 'Matching'), ('map_labelling', 'Plan/Map/Diagram Labelling'), ('short_answer', 'Short Answer'), ('matching_headings', 'Matching Headings'), ('tfng', 'True/False/Not Given')], max_length=20)),
                ('korinish', models.CharField(choices=[('private', 'Shaxsiy'), ('public', 'Umumiy')], default='private', max_length=10)),
                ('matn', models.TextField(blank=True, help_text="Reading passage / ko'rsatma")),
                ('audio_fayl', models.FileField(blank=True, upload_to='mashqlar/audio/')),
                ('rasm', models.ImageField(blank=True, help_text='Plan/Map/Diagram Labelling uchun', upload_to='mashqlar/rasm/')),
                ('savollar', models.JSONField(help_text='Ro\'yxat: [{"savol": "...", "variantlar": ["A", "B"], "togri": "A"}] — "togri" ro\'yxat ham bo\'lishi mumkin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('markaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mashqlar', to='accounts.markaz')),
            ],
            options={
                'verbose_name_plural': 'Mashqlar',
            },
        ),
        migrations.CreateModel(
            name='MashqYechim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('javoblar', models.JSONField()),
                ('ball', models.PositiveIntegerField()),
                ('jami', models.PositiveIntegerField()),
                ('natijalar', models.JSONField(help_text="Har savol bo'yicha [true/false]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mashq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yechimlar', to='exercises.mashq')),
                ('talaba', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='mashq_yechimlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mashq yechimlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
