# Generated by Django 6.0.7 on 2026-07-15 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolim', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading')], max_length=10)),
                ('sana', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talaba', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='limit_topuplar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Limit to'ldiruvlari",
            },
        ),
    ]
