# Generated by Django 6.0.7 on 2026-07-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_limittopup'),
    ]

    operations = [
        migrations.AddField(
            model_name='mashq',
            name='namuna_javob',
            field=models.TextField(blank=True, help_text='Writing/Speaking uchun namuna javob (ixtiyoriy)'),
        ),
        migrations.AlterField(
            model_name='limittopup',
            name='bolim',
            field=models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mashq',
            name='bolim',
            field=models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mashq',
            name='matn',
            field=models.TextField(blank=True, help_text="Reading passage / Writing topshirig'i / Speaking savoli"),
        ),
        migrations.AlterField(
            model_name='mashq',
            name='rasm',
            field=models.ImageField(blank=True, help_text='Plan/Map/Diagram Labelling yoki Writing Task 1 grafigi uchun', upload_to='mashqlar/rasm/'),
        ),
        migrations.AlterField(
            model_name='mashq',
            name='savollar',
            field=models.JSONField(blank=True, default=list, help_text='Ro\'yxat: [{"savol": "...", "variantlar": ["A", "B"], "togri": "A"}] — "togri" ro\'yxat ham bo\'lishi mumkin. Writing/Speaking uchun bo\'sh qoldirilishi mumkin.'),
        ),
        migrations.AlterField(
            model_name='mashq',
            name='tur',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blanks', 'Fill in the Blanks'), ('matching', 'Matching'), ('map_labelling', 'Plan/Map/Diagram Labelling'), ('short_answer', 'Short Answer'), ('matching_headings', 'Matching Headings'), ('tfng', 'True/False/Not Given'), ('task1', 'Writing Task 1'), ('task2', 'Writing Task 2'), ('part1', 'Speaking Part 1'), ('part2', 'Speaking Part 2'), ('part3', 'Speaking Part 3')], max_length=20),
        ),
    ]
