# Generated by Django 6.0.7 on 2026-07-19 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        ('exercises', '0003_mashq_namuna_javob_alter_limittopup_bolim_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImtihonTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bolim', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening')], max_length=10)),
                ('korinish', models.CharField(choices=[('private', 'Shaxsiy'), ('public', 'Umumiy')], default='private', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('markaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imtihon_testlari', to='accounts.markaz')),
            ],
            options={
                'verbose_name_plural': 'Imtihon testlari',
            },
        ),
        migrations.CreateModel(
            name='TestYechim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('javoblar', models.JSONField()),
                ('ball', models.PositiveIntegerField()),
                ('jami', models.PositiveIntegerField()),
                ('natijalar', models.JSONField()),
                ('band', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talaba', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='imtihon_yechimlari', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yechimlar', to='exercises.imtihontest')),
            ],
            options={
                'verbose_name_plural': 'Imtihon yechimlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestQismi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tartib', models.PositiveSmallIntegerField()),
                ('sarlavha', models.CharField(blank=True, help_text="masalan 'Passage 1'", max_length=200)),
                ('yoriqnoma', models.CharField(blank=True, help_text="masalan 'You should spend about 20 minutes on Questions 1-13.'", max_length=300)),
                ('matn', models.TextField(blank=True, help_text='Reading passage matni')),
                ('audio_fayl', models.FileField(blank=True, upload_to='imtihon/audio/')),
                ('savollar', models.JSONField(default=list, help_text='Ro\'yxat: [{"savol": "...", "tur": "multiple_choice", "variantlar": ["A", "B"], "togri": "A", "guruh_boshi": "Questions 1-7" (ixtiyoriy)}]')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qismlar', to='exercises.imtihontest')),
            ],
            options={
                'verbose_name_plural': 'Test qismlari',
                'ordering': ['tartib'],
                'unique_together': {('test', 'tartib')},
            },
        ),
    ]
