# Generated by Django 6.0.7 on 2026-07-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_imtihontest_testyechim_testqismi'),
    ]

    operations = [
        migrations.AddField(
            model_name='testqismi',
            name='rasm',
            field=models.ImageField(blank=True, help_text='Plan/Map/Diagram Labelling yoki Writing Task 1 grafigi uchun', upload_to='imtihon/rasm/'),
        ),
    ]
