# Generated by Django 6.0.7 on 2026-07-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_testqismi_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='testqismi',
            name='tur',
            field=models.CharField(blank=True, choices=[('multiple_choice', 'Multiple Choice'), ('fill_blanks', 'Fill in the Blanks'), ('matching', 'Matching'), ('map_labelling', 'Plan/Map/Diagram Labelling'), ('short_answer', 'Short Answer'), ('matching_headings', 'Matching Headings'), ('tfng', 'True/False/Not Given'), ('task1', 'Writing Task 1'), ('task2', 'Writing Task 2'), ('part1', 'Speaking Part 1'), ('part2', 'Speaking Part 2'), ('part3', 'Speaking Part 3')], help_text="Faqat Writing/Speaking uchun: task1/task2/part1/part2/part3. Reading/Listening'da savol turlari 'savollar' ichida, bu yerda bo'sh qoladi.", max_length=20),
        ),
        migrations.AlterField(
            model_name='imtihontest',
            name='bolim',
            field=models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=10),
        ),
        migrations.AlterField(
            model_name='testqismi',
            name='matn',
            field=models.TextField(blank=True, help_text='Reading passage matni / Writing-Speaking uchun savol-topshiriq matni'),
        ),
        migrations.AlterField(
            model_name='testqismi',
            name='savollar',
            field=models.JSONField(blank=True, default=list, help_text='Reading/Listening uchun ro\'yxat: [{"savol": "...", "tur": "multiple_choice", "variantlar": ["A", "B"], "togri": "A", "guruh_boshi": "Questions 1-7" (ixtiyoriy)}]. Writing/Speaking\'da bo\'sh qoladi — javob AI orqali baholanadi.'),
        ),
    ]
