# Generated by Django 6.0.7 on 2026-07-22 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_testqismi_tur_alter_imtihontest_bolim_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imtihontest',
            name='yaratuvchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yaratgan_imtihon_testlari', to=settings.AUTH_USER_MODEL),
        ),
    ]
