# Generated by Django 6.0.7 on 2026-07-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_imtihontest_yaratuvchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mashq',
            name='sun_iy_intellekt_yaratgan',
            field=models.BooleanField(default=False, help_text="Mashq management-buyruq orqali (masalan wordapp_import, listening_yangi_mashqlar, writing_speaking_yangi_mashqlar) AI yordamida ommaviy yaratilganmi — talabaga 'SI tomonidan tuzilgan' belgisi ko'rsatish uchun. Admin UI orqali qo'lda kiritilgan mashqlarda False qoladi."),
        ),
    ]
