# Generated by Django 6.0.7 on 2026-07-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_belgila_mavjud_seed_mashqlarni_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='testqismi',
            name='maxsus_format',
            field=models.JSONField(blank=True, help_text='Ixtiyoriy — Table/Note/Summary/Flow-chart Completion uchun, javoblarni oddiy ro\'yxat o\'rniga asl kitobdagidek jadval/blok-sxema ko\'rinishida ko\'rsatish (2026-07-24). Grading\'ga ta\'sir qilmaydi — faqat ko\'rinish (render) uchun, javob/to\'g\'ri javob hamon \'savollar\'da saqlanadi. Format: {"tur": "jadval", "sarlavha": "...", "ustunlar": ["...", "..."], "qatorlar": [["katak matni {{1}} bilan", "...", "..."], ...]} yoki {"tur": "oqim", "sarlavha": "...", "qadamlar": ["matn {{26}} bilan", "..."]}. {{n}} — o\'sha savolning testdagi UMUMIY (uzluksiz) raqami, shu joyda kichik input avtomatik chiqadi.', null=True),
        ),
    ]
