# Generated by Django 6.0.7 on 2026-07-26 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        ('exercises', '0010_testqismi_maxsus_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImtihonMock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('korinish', models.CharField(choices=[('private', 'Shaxsiy'), ('public', 'Umumiy')], default='private', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exercises.imtihontest')),
                ('markaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imtihon_moklari', to='accounts.markaz')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exercises.imtihontest')),
                ('speaking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exercises.imtihontest')),
                ('writing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exercises.imtihontest')),
                ('yaratuvchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mock imtihonlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockYechim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_band', models.FloatField(blank=True, null=True)),
                ('speaking_band', models.FloatField(blank=True, null=True)),
                ('overall_band', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tugallandi_at', models.DateTimeField(blank=True, null=True)),
                ('listening_yechim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exercises.testyechim')),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yechimlar', to='exercises.imtihonmock')),
                ('reading_yechim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exercises.testyechim')),
                ('talaba', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='mock_yechimlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mock yechimlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
