# Generated by Django 6.0.7 on 2026-07-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_imtihonmock_mockyechim'),
    ]

    operations = [
        migrations.AddField(
            model_name='imtihonmock',
            name='manba',
            field=models.CharField(choices=[('admin', 'Admin yuklagan'), ('ai', 'AI generatsiya qilgan')], default='admin', help_text="Mock qaysi bo'limda ko'rinadi — admin yoki AI", max_length=10),
        ),
        migrations.AddField(
            model_name='imtihontest',
            name='manba',
            field=models.CharField(choices=[('admin', 'Admin yuklagan'), ('ai', 'AI generatsiya qilgan')], default='admin', help_text='Testni kim yaratgan — admin (IELTS testlari) yoki AI (AI mashqlari)', max_length=10),
        ),
    ]
