# Generated by Django 6.0.7 on 2026-08-01 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_korish_rejimi'),
        ('exercises', '0012_imtihonmock_manba_imtihontest_manba'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPapkasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=120)),
                ('bolim', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=10)),
                ('manba', models.CharField(choices=[('admin', 'Admin yuklagan'), ('ai', 'AI generatsiya qilgan')], default='admin', max_length=10)),
                ('tartib', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('markaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_papkalari', to='accounts.markaz')),
            ],
            options={
                'verbose_name_plural': 'Test papkalari',
                'ordering': ['tartib', 'nomi'],
            },
        ),
        migrations.AddField(
            model_name='imtihontest',
            name='papka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testlar', to='exercises.testpapkasi'),
        ),
    ]
