# Generated by Django 6.0.7 on 2026-08-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_testpapkasi_imtihontest_papka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpapkasi',
            name='bolim',
        ),
    ]
