# Generated by Django 6.0.7 on 2026-08-11 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_remove_testpapkasi_bolim'),
    ]

    operations = [
        migrations.AddField(
            model_name='imtihonmock',
            name='papka',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock', to='exercises.testpapkasi'),
        ),
        migrations.AddField(
            model_name='testpapkasi',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Faqat 1-darajali papkaga bog'lanadi — ichki papkaning o'ziga yana ichki papka bo'lmaydi.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ichki_papkalar', to='exercises.testpapkasi'),
        ),
    ]
