# Generated by Django 6.0.7 on 2026-08-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0015_papka_ichki_va_mock_bogliq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LimitTopUp',
        ),
    ]
