# Generated by Django 6.0.7 on 2026-09-14 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_guruh_faol'),
        ('accounts', '0024_alter_zaxira_unique_together_and_more'),
        ('courses', '0022_grammar_spot_javoblari'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sozlama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boshlangich_oy', models.DateField(help_text='Tizim yoqilgan oy — undan OLDINGI oylarga avtomatik hisob ochilmaydi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sozlamalar',
            },
        ),
        migrations.CreateModel(
            name='AzolikMoliya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(choices=[('sinov', 'Sinov'), ('faol', 'Faol'), ('muzlatilgan', 'Muzlatilgan'), ('arxiv', 'Arxiv')], db_index=True, default='faol', help_text="Faqat 'faol' holatdagi a'zolikka hisob ochiladi", max_length=15)),
                ('boshlanish_sana', models.DateField(help_text="Talaba shu guruhda boshlagan sana (standart — a'zolik yaratilgan kun, lekin tahrirlanadi)")),
                ('tugash_sana', models.DateField(blank=True, help_text="Guruhdan chiqqan sana — o'sha oy proporsional qayta hisoblanadi", null=True)),
                ('qayta_faol_sana', models.DateField(blank=True, null=True)),
                ('narx', models.DecimalField(blank=True, decimal_places=2, help_text='Ixtiyoriy — guruh va kurs narxini bekor qiladi (aka-uka chegirmasi va h.k.)', max_digits=12, null=True)),
                ('oxirgi_hisob_oy', models.DateField(blank=True, db_index=True, help_text="Hisob generatsiyasi shu a'zolik uchun qaysi oygacha yetgani (doim oyning 1-sanasi)", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('azolik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moliya', to='academics.guruhazoligi')),
            ],
            options={
                'verbose_name_plural': "A'zolik moliyasi",
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('manzil', models.CharField(blank=True, max_length=300)),
                ('telefon', models.CharField(blank=True, max_length=30)),
                ('faol', models.BooleanField(default=True, help_text="False bo'lsa — arxivlangan, ro'yxatlarda ko'rinmaydi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('markaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_filiallar', to='accounts.markaz')),
            ],
            options={
                'verbose_name_plural': 'Filiallar',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='GuruhMoliya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narx', models.DecimalField(blank=True, decimal_places=2, help_text="Ixtiyoriy — kurs narxini bekor qiladi. Bo'sh bo'lsa daraja narxi olinadi", max_digits=12, null=True)),
                ('boshlanish_sana', models.DateField(blank=True, help_text="Guruh ochilgan sana — birinchi oy shunga qarab proporsional bo'ladi", null=True)),
                ('tugash_sana', models.DateField(blank=True, help_text='Guruh tugaydigan sana', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guruhlar', to='crm.filial')),
                ('guruh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moliya', to='academics.guruh')),
            ],
            options={
                'verbose_name_plural': 'Guruh moliyasi',
            },
        ),
        migrations.CreateModel(
            name='Hisob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talaba_ism', models.CharField(help_text="Nom nusxasi — talaba o'chirilsa ham qoladi", max_length=200)),
                ('guruh_nomi', models.CharField(help_text="Nom nusxasi — guruh o'chirilsa ham qoladi", max_length=200)),
                ('oy', models.DateField(help_text='Doim oyning 1-sanasi (2026-09-01)')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proporsional', models.BooleanField(default=False, help_text="To'liq oy emas — guruh yoki talaba oy o'rtasida boshlagan/tugatgan")),
                ('darslar_jami', models.PositiveSmallIntegerField(blank=True, help_text='Oydagi BARCHA dars kunlari (diagnostika uchun)', null=True)),
                ('darslar_talaba', models.PositiveSmallIntegerField(blank=True, help_text='Shundan talabaga tegishlisi (diagnostika uchun)', null=True)),
                ('holat', models.CharField(choices=[('qarzdor', 'Qarzdor'), ('qisman', "Qisman to'langan"), ('tolandi', "To'langan")], db_index=True, default='qarzdor', help_text="FAQAT `crm.mantiq.hisobni_yangila()` yozadi — boshqa hech qayerda qo'lda o'zgartirilmaydi", max_length=10)),
                ('qolda', models.BooleanField(default=False, help_text="Admin qo'lda kiritgan (boshlang'ich qarz), avtomatik generatsiya emas")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hisoblar', to='crm.filial')),
                ('guruh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_hisoblari', to='academics.guruh')),
                ('talaba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_hisoblari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hisoblar',
                'ordering': ['-oy', 'guruh_nomi', 'talaba_ism'],
            },
        ),
        migrations.CreateModel(
            name='KursNarxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narx', models.DecimalField(decimal_places=2, help_text="Oylik narx, so'm", max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daraja', models.OneToOneField(help_text='Kurslar daraxtidagi daraja tuguni (Beginner, IELTS, CEFR...)', on_delete=django.db.models.deletion.CASCADE, related_name='crm_narxi', to='courses.kurstugun')),
            ],
            options={
                'verbose_name_plural': 'Kurs narxlari',
            },
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talaba_ism', models.CharField(max_length=200)),
                ('guruh_nomi', models.CharField(max_length=200)),
                ('sana', models.DateField(help_text='Pul haqiqatda kelgan/chiqqan sana')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('turi', models.CharField(choices=[('tolov', "To'lov"), ('chegirma', 'Chegirma'), ('bonus', 'Bonus'), ('qaytarish', 'Pul qaytarish')], db_index=True, default='tolov', max_length=10)),
                ('izoh', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guruh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_tolovlari', to='academics.guruh')),
                ('hisob', models.ForeignKey(blank=True, help_text="Qaysi oy uchun. `qaytarish` uchun odatda bo'sh — u oyga bog'lanmaydi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tolovlar', to='crm.hisob')),
                ('kim_kiritdi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_kiritgan_tolovlari', to=settings.AUTH_USER_MODEL)),
                ('talaba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_tolovlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-sana', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DarsJadvali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hafta_kuni', models.PositiveSmallIntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')])),
                ('boshlanish_vaqti', models.TimeField()),
                ('tugash_vaqti', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_jadval', to='academics.guruh')),
            ],
            options={
                'verbose_name_plural': 'Dars jadvallari',
                'ordering': ['hafta_kuni', 'boshlanish_vaqti'],
                'constraints': [models.UniqueConstraint(fields=('guruh', 'hafta_kuni', 'boshlanish_vaqti'), name='crm_jadval_takrorlanmasin')],
            },
        ),
        migrations.AddConstraint(
            model_name='hisob',
            constraint=models.UniqueConstraint(fields=('talaba', 'guruh', 'oy'), name='crm_hisob_unikal'),
        ),
    ]
