# Generated by Django 6.0.7 on 2026-09-14 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(help_text="Masalan '2-xona'", max_length=100)),
                ('sigimi', models.PositiveSmallIntegerField(blank=True, help_text="Nechta o'quvchi sig'adi (ixtiyoriy)", null=True)),
                ('tartib', models.PositiveSmallIntegerField(default=0, help_text='Setkada qaysi tartibda turishi')),
                ('faol', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xonalar', to='crm.filial')),
            ],
            options={
                'verbose_name_plural': 'Xonalar',
                'ordering': ['filial__nomi', 'tartib', 'nomi'],
            },
        ),
        migrations.AddField(
            model_name='darsjadvali',
            name='xona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='darslar', to='crm.xona'),
        ),
        migrations.AddConstraint(
            model_name='xona',
            constraint=models.UniqueConstraint(fields=('filial', 'nomi'), name='crm_xona_filialda_unikal'),
        ),
    ]
