# Generated by Django 6.0.7 on 2026-09-15 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_guruh_faol'),
        ('crm', '0002_xona_darsjadvali_xona_xona_crm_xona_filialda_unikal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eslatma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guruh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_eslatmalari', to='academics.guruh')),
                ('kim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_yozgan_eslatmalari', to=settings.AUTH_USER_MODEL)),
                ('talaba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_eslatmalari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Eslatmalar',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('guruh__isnull', False), ('talaba__isnull', False), _connector='OR'), name='crm_eslatma_egasi_bolsin')],
            },
        ),
    ]
