# Generated by Django 6.0.7 on 2026-09-23 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_guruh_faol'),
        ('courses', '0023_intermediate_mashq_shakllari'),
        ('crm', '0003_eslatma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chegirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narx', models.DecimalField(decimal_places=2, help_text='Chegirmadagi oylik narx (0 = tekin)', max_digits=12)),
                ('boshlanish_oy', models.DateField(help_text='Doim oyning 1-sanasi')),
                ('oylar_soni', models.PositiveSmallIntegerField(default=1)),
                ('izoh', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Chegirmalar',
                'ordering': ['-boshlanish_oy', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CrmRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, unique=True)),
                ('faol', models.BooleanField(default=True)),
                ('ruxsatlar', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'CRM rollari',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='DarsBahosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('ball', models.DecimalField(decimal_places=1, max_digits=5)),
                ('izoh', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DarsOzgarish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('kochirish', "Ko'chirildi"), ('qoshimcha', "Qo'shimcha dars"), ('bekor', 'Bekor qilindi')], max_length=10)),
                ('asl_sana', models.DateField(blank=True, help_text="Ko'chirilgan/bekor qilingan dars sanasi", null=True)),
                ('yangi_sana', models.DateField(blank=True, help_text="Ko'chirilgan/qo'shimcha dars sanasi", null=True)),
                ('boshlanish_vaqti', models.TimeField(blank=True, null=True)),
                ('tugash_vaqti', models.TimeField(blank=True, null=True)),
                ('mavzu', models.CharField(blank=True, max_length=200)),
                ('izoh', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DavomatIzoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sababli', models.BooleanField(default=False)),
                ('izoh', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GuruhOqituvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('asosiy', 'Asosiy'), ('yordamchi', 'Yordamchi')], default='asosiy', max_length=10)),
                ('ulush_turi', models.CharField(choices=[('foiz', 'Tushumdan foiz'), ('dars', 'Har dars uchun summa')], default='foiz', max_length=5)),
                ('foiz', models.DecimalField(blank=True, decimal_places=2, help_text="Shu guruh tushumidan ulush, %. Bo'sh — xodim profilidagi umumiy foiz", max_digits=5, null=True)),
                ('dars_haqi', models.DecimalField(blank=True, decimal_places=2, help_text="ulush_turi='dars' bo'lsa — bitta o'tilgan dars uchun, so'm", max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=20)),
                ('qoshimcha_telefon', models.CharField(blank=True, max_length=20)),
                ('qoshimcha_ism', models.CharField(blank=True, help_text="Qo'shimcha raqam egasi (masalan 'oyisi Hilola opa')", max_length=100)),
                ('tugilgan_sana', models.DateField(blank=True, null=True)),
                ('manba', models.CharField(blank=True, max_length=100)),
                ('holat', models.CharField(choices=[('yangi', 'Yangi'), ('boglanildi', "Bog'lanildi"), ('sinov', 'Sinov darsida'), ('kelmadi', 'Kelmadi'), ('oylayapti', "O'ylayapti"), ('yoqotilgan', "Yo'qotilgan"), ('qoshildi', "Guruhga qo'shildi")], db_index=True, default='yangi', max_length=12)),
                ('qulay_vaqt', models.CharField(blank=True, max_length=50)),
                ('kunlar', models.CharField(blank=True, help_text='toq / juft / har_kuni / boshqa', max_length=20)),
                ('izoh', models.CharField(blank=True, max_length=500)),
                ('arxiv', models.BooleanField(db_index=True, default=False)),
                ('qora_royxat', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lidlar',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LidBolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tartib', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "Lid bo'limlari",
                'ordering': ['tartib', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LidTarix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TalabaProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jins', models.CharField(blank=True, choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=5)),
                ('maktab', models.CharField(blank=True, max_length=100)),
                ('qora_royxat', models.BooleanField(db_index=True, default=False)),
                ('qora_royxat_sabab', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Talaba profillari',
            },
        ),
        migrations.CreateModel(
            name='XodimProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavozim', models.CharField(choices=[('admin', 'Administrator'), ('ceo', 'CEO'), ('oqituvchi', "O'qituvchi"), ('support', 'Support teacher'), ('kassir', 'Kassir'), ('marketolog', 'Marketolog'), ('watcher', 'Kuzatuvchi'), ('boshqa', 'Boshqa')], db_index=True, default='boshqa', max_length=12)),
                ('jins', models.CharField(blank=True, choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=5)),
                ('ishga_olingan_sana', models.DateField(blank=True, null=True)),
                ('oylik', models.DecimalField(decimal_places=2, default=0, help_text="Doimiy oylik, so'm", max_digits=12)),
                ('foiz_ulushi', models.DecimalField(decimal_places=2, default=0, help_text="Guruh tushumidan ulush, % (o'qituvchi uchun)", max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Xodim profillari',
            },
        ),
        migrations.RemoveConstraint(
            model_name='eslatma',
            name='crm_eslatma_egasi_bolsin',
        ),
        migrations.AddField(
            model_name='eslatma',
            name='eslatish_vaqti',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guruhmoliya',
            name='baholash_tizimi',
            field=models.CharField(blank=True, choices=[('5', '1-5 ball'), ('10', '1-10 ball'), ('100', '100 ball')], max_length=5),
        ),
        migrations.AddField(
            model_name='tolov',
            name='usul',
            field=models.CharField(blank=True, choices=[('naqd', 'Naqd'), ('karta', 'Plastik karta'), ('click', 'Click'), ('payme', 'Payme'), ('otkazma', "Bank o'tkazmasi")], default='naqd', help_text="Faqat 'tolov' va 'qaytarish' uchun ma'noli", max_length=10),
        ),
        migrations.AddField(
            model_name='chegirma',
            name='azolik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chegirmalar', to='crm.azolikmoliya'),
        ),
        migrations.AddField(
            model_name='chegirma',
            name='kim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='darsbahosi',
            name='guruh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_baholar', to='academics.guruh'),
        ),
        migrations.AddField(
            model_name='darsbahosi',
            name='kim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='darsbahosi',
            name='talaba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_baholar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='darsozgarish',
            name='guruh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_dars_ozgarishlari', to='academics.guruh'),
        ),
        migrations.AddField(
            model_name='darsozgarish',
            name='kim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='darsozgarish',
            name='xona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.xona'),
        ),
        migrations.AddField(
            model_name='davomatizoh',
            name='davomat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_izoh', to='academics.davomat'),
        ),
        migrations.AddField(
            model_name='guruhoqituvchi',
            name='guruh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_oqituvchilar', to='academics.guruh'),
        ),
        migrations.AddField(
            model_name='guruhoqituvchi',
            name='oqituvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_guruh_ulushlari', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lid',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lidlar', to='crm.filial'),
        ),
        migrations.AddField(
            model_name='lid',
            name='kim_qoshdi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_qoshgan_lidlari', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lid',
            name='kurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_lidlari', to='courses.kurstugun'),
        ),
        migrations.AddField(
            model_name='lid',
            name='oqituvchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_lidlari_oqituvchi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lid',
            name='talaba',
            field=models.ForeignKey(blank=True, help_text="Lid talabaga aylangandan keyin — o'sha talaba", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_lid_manbasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eslatma',
            name='lid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eslatmalar', to='crm.lid'),
        ),
        migrations.AddConstraint(
            model_name='eslatma',
            constraint=models.CheckConstraint(condition=models.Q(('guruh__isnull', False), ('talaba__isnull', False), ('lid__isnull', False), _connector='OR'), name='crm_eslatma_egasi_bolsin_v2'),
        ),
        migrations.AddField(
            model_name='lidbolim',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lid_bolimlari', to='crm.filial'),
        ),
        migrations.AddField(
            model_name='lid',
            name='bolim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lidlar', to='crm.lidbolim'),
        ),
        migrations.AddField(
            model_name='lidtarix',
            name='kim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lidtarix',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarix', to='crm.lid'),
        ),
        migrations.AddField(
            model_name='talabaprofil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_talaba', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xodimprofil',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xodimlar', to='crm.filial'),
        ),
        migrations.AddField(
            model_name='xodimprofil',
            name='rol',
            field=models.ForeignKey(blank=True, help_text="Maxsus rol — bo'lsa, ruxsatlar shundan olinadi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xodimlar', to='crm.crmrol'),
        ),
        migrations.AddField(
            model_name='xodimprofil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_xodim', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='darsbahosi',
            constraint=models.UniqueConstraint(fields=('guruh', 'talaba', 'sana'), name='crm_baho_unikal'),
        ),
        migrations.AddConstraint(
            model_name='guruhoqituvchi',
            constraint=models.UniqueConstraint(fields=('guruh', 'oqituvchi'), name='crm_guruh_oqituvchi_unikal'),
        ),
    ]
