# Generated by Django 6.0.7 on 2026-09-23 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_guruh_faol'),
        ('crm', '0004_video_tz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LidDoska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tartib', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tartib', 'id'],
            },
        ),
        migrations.AddField(
            model_name='hisob',
            name='izoh',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='lid',
            name='harorat',
            field=models.CharField(blank=True, choices=[('issiq', 'Issiq'), ('iliq', 'Iliq'), ('sovuq', 'Sovuq')], max_length=6),
        ),
        migrations.AddField(
            model_name='lidbolim',
            name='guruh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.guruh'),
        ),
        migrations.AlterField(
            model_name='lid',
            name='holat',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('boglanildi', "Bog'lanildi"), ('boglana_olmadi', "Bog'lana olmadi"), ('sinov', 'Sinov darsida'), ('kelmadi', 'Kelmadi'), ('oylayapti', "O'ylayapti"), ('yoqotilgan', "Yo'qotilgan"), ('qoshildi', "Guruhga qo'shildi")], db_index=True, default='yangi', max_length=16),
        ),
        migrations.AlterField(
            model_name='tolov',
            name='usul',
            field=models.CharField(blank=True, choices=[('naqd', 'Naqd'), ('karta', 'Plastik karta'), ('click', 'Click'), ('payme', 'Payme'), ('otkazma', "Bank o'tkazmasi"), ('qr', 'Yagona QR-kod'), ('voucher', 'Voucher')], default='naqd', help_text="Faqat 'tolov' va 'qaytarish' uchun ma'noli", max_length=10),
        ),
        migrations.CreateModel(
            name='GuruhdanChiqish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talaba_ism', models.CharField(max_length=200)),
                ('guruh_nomi', models.CharField(max_length=200)),
                ('boshlagan_sana', models.DateField(blank=True, null=True)),
                ('sana', models.DateField(help_text='Chiqqan sana')),
                ('sabab', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.filial')),
                ('guruh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.guruh')),
                ('kim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('talaba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_chiqishlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sana', '-id'],
            },
        ),
        migrations.AddField(
            model_name='lidbolim',
            name='doska',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ustunlar', to='crm.liddoska'),
        ),
        migrations.CreateModel(
            name='DarsMavzusi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('mavzu', models.CharField(max_length=200)),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_mavzular', to='academics.guruh')),
                ('kim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('guruh', 'sana'), name='crm_mavzu_unikal')],
            },
        ),
        migrations.CreateModel(
            name='XodimDavomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('holat', models.CharField(choices=[('keldi', 'Keldi'), ('kechikdi', 'Kechikdi'), ('kelmadi', 'Kelmadi'), ('sababli', 'Sababli')], max_length=10)),
                ('izoh', models.CharField(blank=True, max_length=300)),
                ('kim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_davomat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('xodim', 'sana'), name='crm_xodim_davomat_unikal')],
            },
        ),
    ]
