# Generated by Django 6.0.7 on 2026-09-23 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_guruh_faol'),
        ('crm', '0005_video_tz_qayta'),
    ]

    operations = [
        migrations.AddField(
            model_name='lid',
            name='yigilayotgan_guruh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.guruh'),
        ),
    ]
