# Generated by Django 6.0.7 on 2026-09-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_lid_doska_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='azolikmoliya',
            name='muzlatish_izoh',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='azolikmoliya',
            name='muzlatish_sana',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guruhdanchiqish',
            name='chegirma_bor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guruhdanchiqish',
            name='oylik_narx',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='guruhdanchiqish',
            name='sabab_turi',
            field=models.CharField(choices=[('joylashuv', 'Joylashuv'), ('narx', 'Narx'), ('natija', 'Natija'), ('dars_jadvali', 'Dars jadvali'), ('oqituvchi', "O'qituvchi"), ('boshqa', 'Boshqa sabablar'), ('lidga', 'Lidlarga qaytarildi'), ('bitirdi', 'Kursni bitirdi'), ('kochirildi', "Boshqa guruhga o'tdi")], default='boshqa', max_length=15),
        ),
        migrations.AddField(
            model_name='lid',
            name='arxiv_izoh',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='lid',
            name='arxiv_sabab',
            field=models.CharField(blank=True, choices=[('kelmadi', 'Kelaman deb kelmadi'), ('raqobatchi', 'Raqobatchiga ketdi'), ('boshqa_filial', 'Boshqa filialga yuborildi'), ('boshqa', 'Boshqa sabab')], max_length=20),
        ),
        migrations.AddField(
            model_name='lid',
            name='qora_royxat_izoh',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='talabaprofil',
            name='arxiv_izoh',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='talabaprofil',
            name='arxiv_sabab',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='guruhdanchiqish',
            name='sabab',
            field=models.CharField(blank=True, help_text='Izoh', max_length=300),
        ),
    ]
