# Generated by Django 6.0.7 on 2026-09-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_video_tz_sabablar'),
    ]

    operations = [
        migrations.AddField(
            model_name='eslatma',
            name='bajarildi',
            field=models.BooleanField(default=False),
        ),
    ]
