"""Davomat izohiga "kechikdi" belgisi (video-TZ 2026-09-28, SoffCRM "Kech qoldi")."""

# Generated by Django 6.0.7 on 2026-09-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_eslatma_bajarildi'),
    ]

    operations = [
        migrations.AddField(
            model_name='davomatizoh',
            name='kechikdi',
            field=models.BooleanField(default=False),
        ),
    ]
