# Generated by Django 6.0.7 on 2026-07-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=200)),
                ('uz', models.CharField(max_length=300)),
                ('daraja', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('idiom', 'Idioma')], max_length=10)),
                ('turkum', models.CharField(blank=True, max_length=50)),
                ('misol', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': "So'zlar",
                'indexes': [models.Index(fields=['daraja'], name='games_soz_daraja_108221_idx')],
            },
        ),
    ]
