# Generated by Django 6.0.7 on 2026-07-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammatikaSavoli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu', models.CharField(max_length=50)),
                ('savol', models.CharField(max_length=300)),
                ('variantlar', models.JSONField()),
                ('togri', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Grammatika savollari',
                'indexes': [models.Index(fields=['mavzu'], name='games_gramm_mavzu_5533bd_idx')],
            },
        ),
    ]
