# Generated by Django 6.0.7 on 2026-09-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_grammatikasavoli'),
    ]

    operations = [
        migrations.AddField(
            model_name='soz',
            name='ru',
            field=models.CharField(blank=True, help_text="2026-09-05: ruscha tarjima. Bo'sh bo'lsa `uz` ishlatiladi — qarang `courses.KursSoz.ru`.", max_length=300),
        ),
    ]
