# Generated by Django 6.0.7 on 2026-07-15 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tavsif', models.TextField(blank=True)),
                ('tartib', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('markaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurslar', to='accounts.markaz')),
                ('yaratgan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yaratgan_kurslar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kurslar',
                'ordering': ['tartib', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Dars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tavsif', models.TextField(blank=True)),
                ('tartib', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darslar', to='content.kurs')),
            ],
            options={
                'verbose_name_plural': 'Darslar',
                'ordering': ['tartib', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('turi', models.CharField(choices=[('matn', 'Matn'), ('video', 'Video (YouTube)'), ('audio', 'Audio')], max_length=10)),
                ('korinish', models.CharField(choices=[('private', "Shaxsiy (faqat o'z markazi)"), ('public', 'Umumiy (almashish tizimi)')], default='private', max_length=10)),
                ('matn', models.TextField(blank=True)),
                ('youtube_id', models.CharField(blank=True, help_text="Faqat video ID (masalan dQw4w9WgXcQ), to'liq URL emas", max_length=20)),
                ('audio_fayl', models.FileField(blank=True, upload_to='materiallar/audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dars', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiallar', to='content.dars')),
                ('markaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiallar', to='accounts.markaz')),
            ],
            options={
                'verbose_name_plural': 'Materiallar',
            },
        ),
        migrations.CreateModel(
            name='DarsFaollik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(choices=[('boshladi', 'Boshladi'), ('tugatdi', 'Tugatdi')], default='boshladi', max_length=10)),
                ('boshlagan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('tugatgan_vaqt', models.DateTimeField(blank=True, null=True)),
                ('talaba', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='dars_faolliklari', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faolliklar', to='content.material')),
            ],
            options={
                'verbose_name_plural': 'Dars faolliklari',
                'constraints': [models.UniqueConstraint(fields=('talaba', 'material'), name='faollik_unikal')],
            },
        ),
    ]
