# Generated by Django 6.0.7 on 2026-07-15 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('markaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guruhlar', to='accounts.markaz')),
                ('oqituvchi', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oqituvchi_guruhlari', to=settings.AUTH_USER_MODEL)),
                ('talabalar', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='talaba_guruhlari', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
