# Generated by Django 6.0.7 on 2026-07-15 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('holat', models.CharField(choices=[('keldi', 'Keldi'), ('kelmadi', 'Kelmadi')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('belgilagan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belgilagan_davomatlar', to=settings.AUTH_USER_MODEL)),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davomatlar', to='academics.guruh')),
                ('talaba', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='davomatlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sana'],
                'constraints': [models.UniqueConstraint(fields=('sana', 'guruh', 'talaba'), name='davomat_unikal')],
            },
        ),
    ]
