# Generated by Django 6.0.7 on 2026-08-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_davomat'),
        ('courses', '0009_kursmashq_bloklar_kursmashqrasmi_kurszipjarayoni'),
    ]

    operations = [
        migrations.AddField(
            model_name='guruh',
            name='daraja',
            field=models.ForeignKey(blank=True, help_text='Tanlangan fan ichidagi daraja (masalan Beginner, IELTS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guruhlar_daraja', to='courses.kurstugun'),
        ),
        migrations.AddField(
            model_name='guruh',
            name='fan',
            field=models.ForeignKey(blank=True, help_text="Kurslar bo'limidagi fan (masalan Ingliz tili)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guruhlar_fan', to='courses.kurstugun'),
        ),
    ]
