# Generated by Django 6.0.7 on 2026-08-02 13:38 (qo'lda tuzatilgan —
# SQLite M2M'ga to'g'ridan-to'g'ri `through=` qo'sha olmaydi, shuning
# uchun RemoveField+AddField, orasida eski ma'lumotni ko'chirish bilan).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _eski_azolikni_kochir(apps, schema_editor):
    """`talabalar` M2M oddiy'dan `through=GuruhAzoligi`ga o'tkazilganda,
    Django avtomatik yaratgan eski `academics_guruh_talabalar` jadvali
    keyingi qadamda (RemoveField) O'CHIRILADI — productionda MAVJUD
    guruh-talaba bog'lanishlari oldindan ko'chirilmasa, BUTUNLAY
    YO'QOLADI (2026-08-02, xavfsizlik tekshiruvi paytida aniqlangan,
    SQLite'da amaliy sinovdan o'tkazilgan). Shu funksiya eski jadvaldagi
    (guruh_id, user_id) qatorlarini yangi jadvalga RemoveField'dan OLDIN
    nusxalaydi."""
    connection = schema_editor.connection
    if "academics_guruh_talabalar" not in connection.introspection.table_names():
        return
    with connection.cursor() as cursor:
        cursor.execute("SELECT guruh_id, user_id FROM academics_guruh_talabalar")
        qatorlar = cursor.fetchall()
    GuruhAzoligi = apps.get_model("academics", "GuruhAzoligi")
    for guruh_id, user_id in qatorlar:
        GuruhAzoligi.objects.get_or_create(guruh_id=guruh_id, talaba_id=user_id)


def _hech_narsa(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_guruh_daraja_guruh_fan'),
        ('courses', '0009_kursmashq_bloklar_kursmashqrasmi_kurszipjarayoni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuruhAzoligi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boshlanish_unit', models.ForeignKey(blank=True, help_text='Guruhning darajasi ichidagi Unit — talaba shundan boshlaydi, oldingilar qulfsiz', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.kurstugun')),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.guruh')),
                ('talaba', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Guruh a'zoliklari",
                'unique_together': {('guruh', 'talaba')},
            },
        ),
        # Eski ma'lumot RemoveField'dan OLDIN ko'chiriladi — buyruq
        # tartibi MUHIM (keyin bo'lsa, manba jadval allaqachon yo'q bo'ladi).
        migrations.RunPython(_eski_azolikni_kochir, _hech_narsa),
        migrations.RemoveField(
            model_name='guruh',
            name='talabalar',
        ),
        migrations.AddField(
            model_name='guruh',
            name='talabalar',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='talaba_guruhlari', through='academics.GuruhAzoligi', to=settings.AUTH_USER_MODEL),
        ),
    ]
