# Generated by Django 6.0.7 on 2026-08-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_guruhazoligi_alter_guruh_talabalar'),
    ]

    operations = [
        migrations.AddField(
            model_name='guruh',
            name='faol',
            field=models.BooleanField(default=True, help_text="False bo'lsa — arxivlangan, ro'yxatlarda ko'rinmaydi"),
        ),
    ]
