# Generated by Django 6.0.7 on 2026-07-15 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalabaBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Talaba badgelari',
                'constraints': [models.UniqueConstraint(fields=('talaba', 'kod'), name='badge_unikal')],
            },
        ),
        migrations.CreateModel(
            name='XPYozuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField()),
                ('sabab', models.CharField(max_length=30)),
                ('manba_id', models.PositiveIntegerField(blank=True, help_text='Hodisa manbai (yechim/tekshiruv/faollik id) — takror bermaslik uchun', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_yozuvlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'XP yozuvlari',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('manba_id__isnull', False)), fields=('talaba', 'sabab', 'manba_id'), name='xp_takror_bermaslik')],
            },
        ),
    ]
