from django.urls import path

from . import blok_views, views

urlpatterns = [
    # Blok formati (2026-07-28) — ZIP bir marta yuklanadi, sahifalar
    # BITTALAB qayta ishlanadi (gunicorn 300s timeout'iga sig'ishi uchun).
    path(
        "kurslar/<int:pk>/blok-zip/",
        blok_views.KursBlokZipYuklashView.as_view(),
        name="kurslar_blok_zip",
    ),
    path(
        "kurslar/<int:pk>/blok-jarayon-holati/",
        blok_views.KursBlokJarayonHolatiView.as_view(),
        name="kurslar_blok_jarayon_holati",
    ),
    path(
        "kurslar/blok-jarayon/<int:pk>/sahifa/",
        blok_views.KursBlokSahifaView.as_view(),
        name="kurslar_blok_sahifa",
    ),
    path(
        "kurslar/blok-jarayon/<int:pk>/tasdiq/",
        blok_views.KursBlokTasdiqView.as_view(),
        name="kurslar_blok_tasdiq",
    ),
    path(
        "kurslar/blok-jarayon/<int:pk>/sahifa-rasm/<int:indeks>/",
        blok_views.KursBlokSahifaRasmiView.as_view(),
        name="kurslar_blok_sahifa_rasmi",
    ),
    path(
        "kurslar/blok-jarayon/<int:pk>/tasdiqla/",
        blok_views.KursBlokTasdiqlashView.as_view(),
        name="kurslar_blok_tasdiqlash",
    ),
    path(
        "kurslar/<int:pk>/mashq-rasm-qoshish/",
        blok_views.KursMashqRasmdanQoshishView.as_view(),
        name="kurslar_mashq_rasm_qoshish",
    ),
    path(
        "kurslar/mashq/<int:pk>/qayta-yuklash/",
        blok_views.KursMashqQaytaYuklashView.as_view(),
        name="kurslar_mashq_qayta_yuklash",
    ),
    path(
        "kurslar/blok-rasm/<int:pk>/",
        views.KursBlokRasmView.as_view(),
        name="kurslar_blok_rasm",
    ),
    path("kurslar/daraxt/", views.KursDaraxtiView.as_view(), name="kurslar_daraxt"),
    path("kurslar/<int:pk>/fayl/", views.KursFaylView.as_view(), name="kurslar_fayl"),
    path(
        "kurslar/<int:pk>/fayl-boshqaruv/",
        views.KursTugunFaylBoshqaruvView.as_view(),
        name="kurslar_fayl_boshqaruv",
    ),
    path(
        "kurslar/<int:pk>/tugallandi/",
        views.KursTugunTugallandiView.as_view(),
        name="kurslar_tugallandi",
    ),
    path(
        "kurslar/<int:pk>/mashq-boshqaruv/",
        views.KursMashqBoshqaruvView.as_view(),
        name="kurslar_mashq_boshqaruv",
    ),
    path(
        "kurslar/<int:pk>/unit-yuklash/",
        views.KursUnitYuklashView.as_view(),
        name="kurslar_unit_yuklash",
    ),
    path(
        "kurslar/<int:pk>/daraja-unit-yaratish/",
        views.KursDarajaUnitYaratishView.as_view(),
        name="kurslar_daraja_unit_yaratish",
    ),
    path(
        "kurslar/<int:pk>/zip-yuklash/",
        views.KursZipYuklashView.as_view(),
        name="kurslar_zip_yuklash",
    ),
    path(
        "kurslar/<int:pk>/unit-tozalash/",
        views.KursUnitTozalashView.as_view(),
        name="kurslar_unit_tozalash",
    ),
    path(
        "kurslar/<int:pk>/eksport/",
        views.KursEksportView.as_view(),
        name="kurslar_eksport",
    ),
    path(
        "kurslar/<int:pk>/import/",
        views.KursImportView.as_view(),
        name="kurslar_import",
    ),
    path(
        "kurslar/<int:pk>/sozlar/",
        views.KursSozlarView.as_view(),
        name="kurslar_sozlar",
    ),
    path(
        "kurslar/<int:pk>/mashqlar/",
        views.KursMashqRoyxatiView.as_view(),
        name="kurslar_mashqlar",
    ),
    path(
        "kurslar/mashq/<int:pk>/",
        views.KursMashqDetailBoshqaruvView.as_view(),
        name="kurslar_mashq_detail",
    ),
    path(
        "kurslar/mashq/<int:pk>/rasm/",
        views.KursMashqRasmView.as_view(),
        name="kurslar_mashq_rasm",
    ),
    path(
        "kurslar/mashq/<int:pk>/rasm-boshqaruv/",
        views.KursMashqRasmBoshqaruvView.as_view(),
        name="kurslar_mashq_rasm_boshqaruv",
    ),
    path(
        "kurslar/mashq/<int:pk>/audio/",
        views.KursMashqAudioView.as_view(),
        name="kurslar_mashq_audio",
    ),
    path(
        "kurslar/mashq-audio/<int:pk>/",
        views.KursMashqAudioKopView.as_view(),
        name="kurslar_mashq_audio_kop",
    ),
    path(
        "kurslar/mashq/<int:pk>/audio-boshqaruv/",
        views.KursMashqAudioBoshqaruvView.as_view(),
        name="kurslar_mashq_audio_boshqaruv",
    ),
    path(
        "kurslar/mashq/<int:pk>/blok-audio-yuklash/",
        views.KursMashqBlokAudioBoshqaruvView.as_view(),
        name="kurslar_mashq_blok_audio_yuklash",
    ),
    path(
        "kurslar/mashq/<int:pk>/javob-excel/",
        views.KursMashqJavobExcelView.as_view(),
        name="kurslar_mashq_javob_excel",
    ),
    path(
        "kurslar/<int:pk>/audio-zip/",
        views.KursMashqAudioZipBoshqaruvView.as_view(),
        name="kurslar_audio_zip",
    ),
    path(
        "kurslar/mashq/<int:pk>/yechish/",
        views.KursMashqYechishView.as_view(),
        name="kurslar_mashq_yechish",
    ),
]
